# Web Scrapping: Used Car Price

In [1]:
import selenium
import pandas as pd
from selenium import webdriver
from selenium.common.exceptions import StaleElementReferenceException
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import ElementClickInterceptedException
from bs4 import BeautifulSoup
import requests
import time

In [76]:
driver = webdriver.Chrome('chromedriver.exe')
time.sleep(2)
url="https://www.olx.in/"
driver.get(url)

In [77]:
driver.find_element_by_xpath("//a[@class='_2fitb']").click()

In [81]:
for i in range(50):
    try:
        driver.execute_script("window.scrollBy(0,40000)")
        time.sleep(1)
        driver.find_element_by_xpath("//button[@class='rui-39-wj rui-3evoE rui-1JPTg']").click()
        time.sleep(1)
    except NoSuchElementException as e:
        print(e)
        break

Message: no such element: Unable to locate element: {"method":"xpath","selector":"//button[@class='rui-39-wj rui-3evoE rui-1JPTg']"}
  (Session info: chrome=93.0.4577.82)

In [82]:
urls=[]
for i in driver.find_elements_by_xpath("//li[@class='EIR5N']/a"):
    urls.append(i.get_attribute("href"))

In [83]:
len(urls)

1000

In [84]:
#Lists
brand=[]
model=[]
variant=[]
year=[]
fuel=[]
transmission=[]
km=[]
owners=[]
location=[]
price=[]

In [85]:
for i in urls:
    driver.get(i)
    time.sleep(1)
    try:
        brand.append(driver.find_element_by_xpath("//div[@class='_35xN1']").text)
    except NoSuchElementException:
        brand.append('-')      
    try:
        model.append(driver.find_element_by_xpath("//div[@class='_35xN1']").text)
    except NoSuchElementException:
        model.append('-')
    try:
        year.append(driver.find_element_by_xpath("//div[@class='_35xN1']").text)
    except NoSuchElementException:
        year.append('-')
    try:
        variant.append(driver.find_element_by_xpath("//div[@class='_3tLee']").text)
    except NoSuchElementException:
        variant.append('-')
    try:
        fuel.append(driver.find_element_by_xpath("/html/body/div/div/main/div/div/div/div[5]/div[1]/div[1]/div[1]/div/div[4]/div[1]/div").text)
    except NoSuchElementException:
        fuel.append('-')
    try:
        transmission.append(driver.find_element_by_xpath("/html/body/div[1]/div/main/div/div/div/div[5]/div[1]/div[1]/div[1]/div/div[4]/div[3]/div").text)
    except NoSuchElementException:
        transmission.append('-')
    try:
        km.append(driver.find_element_by_xpath("/html/body/div/div/main/div/div/div/div[5]/div[1]/div[1]/div[1]/div/div[4]/div[2]/div").text)
    except NoSuchElementException:
        km.append('-')
    try:
        owners.append(driver.find_element_by_xpath("/html/body/div/div/main/div/div/div/div[5]/div[1]/div[2]/div/div[2]/div/div[1]/div[2]/div[2]").text)
    except NoSuchElementException:
        owners.append('-')
    try:
        location.append(driver.find_element_by_xpath("/html/body/div/div/main/div/div/div/div[5]/div[1]/div[2]/div/div[2]/div/div[2]/div[2]/div[2]").text)
    except NoSuchElementException:
        location.append('-')
    try:
        price.append(driver.find_element_by_xpath("//div[@class='_3FkyT']").text)
    except NoSuchElementException:
        price.append('-')

In [31]:
df=pd.DataFrame({})
df['Brand']=brand
df['model']=model
df['variant']=variant
df['year']=year
df['fuel']=fuel
df['transmission']=transmission
df['km driven']=km
df['No of owners']=owners
df['location']=location
df['price']=price
df

,Brand,model,variant,year,fuel,transmission,km driven,No of owners,location,price
0,Ford Figo (2012),Ford Figo (2012),1.5D Ambiente MT,Ford Figo (2012),DIESEL,MANUAL,79000.0 KM,2nd,"Chennai Central, Chennai","₹ 3,00,000"
1,Honda Jazz (2012),Honda Jazz (2012),V,Honda Jazz (2012),PETROL,MANUAL,88000.0 KM,1st,"Andheri East, Mumbai","₹ 3,25,000"
2,-,-,-,-,-,-,-,-,-,-
3,Maruti Suzuki Wagon R (2009),Maruti Suzuki Wagon R (2009),2006-2010 LXI Minor,Maruti Suzuki Wagon R (2009),PETROL,MANUAL,90000 KM,First,"Perumbadappu, Kochi","₹ 1,65,000"
4,Mahindra Scorpio (2008),Mahindra Scorpio (2008),2006-2009 SLX 2.6 Turbo 7 Str,Mahindra Scorpio (2008),DIESEL,MANUAL,125521 KM,First,"Chembur, Mumbai","₹ 2,70,000"
...,...,...,...,...,...,...,...,...,...,...
75,Mahindra Tuv 300 (2018),Mahindra Tuv 300 (2018),T10 AMT (Automatic),Mahindra Tuv 300 (2018),DIESEL,AUTOMATIC,48 KM,2nd,"Wahal Village, Navi Mumbai","₹ 8,00,000"
76,Tata Nano (2011),Tata Nano (2011),2012-2015 LX,Tata Nano (2011),PETROL,MANUAL,"93,000 KM",3rd,"Mathara, Olavanna","₹ 55,000"
77,Hyundai I10 (2010),Hyundai I10 (2010),2007-2010 Magna 1.2,Hyundai I10 (2010),PETROL,MANUAL,"55,000 KM",1st,"Aaram Chowk, Kolhapur","₹ 2,18,000"
78,Jeep Compass (2020),Jeep Compass (2020),Others,Jeep Compass (2020),PETROL,AUTOMATIC,11000.0 KM,1st,"Noida Extension, Noida","₹ 22,00,000"
79,Honda Jazz (2019),Honda Jazz (2019),VX,Honda Jazz (2019),PETROL,AUTOMATIC,23098.0 KM,1st,"Tumkur Road, Bengaluru","₹ 8,75,000"

In [86]:
df.to_csv("olx.csv")

In [5]:
driver = webdriver.Chrome('chromedriver.exe')
driver.get("https://www.cardekho.com/")

In [6]:
driver.get(driver.find_element_by_xpath("//nav[@class='gsc_col-sm-12 gsc_col-md-12']/ul/li[2]/ul/li/ul/li/a").get_attribute("href"))

In [7]:
for i in range(600):
    driver.execute_script("window.scrollBy(0,100)")
    time.sleep(1)

In [8]:
urls=[]
for i in driver.find_elements_by_xpath("//div[@class='gsc_col-xs-7 carsName']/a"):
    urls.append(i.get_attribute("href"))

In [9]:
len(urls)

335

In [10]:
brand=[]
model=[]
variant=[]
year=[]
fuel=[]
transmission=[]
km=[]
owners=[]
location=[]
price=[]

In [11]:
for i in urls:
    driver.get(i)
    time.sleep(1)
    try:
        brand.append(driver.find_element_by_xpath("//div[@class='gsc_col-xs-12']/h1").text)
    except NoSuchElementException:
        brand.append(driver.find_element_by_xpath("//div[@class='vdp-head']").text)
    except:
        brand.append('-')
    try:
        model.append(driver.find_element_by_xpath("//div[@class='gsc_col-xs-12']/h1").text)
    except NoSuchElementException:
        model.append(driver.find_element_by_xpath("//div[@class='vdp-head']").text)
    except:
        model.append('-')
    try:
        variant.append(driver.find_element_by_xpath("//div[@class='variant-name']").text)
    except NoSuchElementException:
        variant.append(driver.find_element_by_xpath("//div[@class='vdp-head']").text)
    except:
        variant.append('-')
    try:
        year.append(driver.find_element_by_xpath("//div[@class='gsc_col-xs-12']/ul/li[1]/div/div[2]").text)
    except NoSuchElementException:
        year.append(driver.find_element_by_xpath("//ul[@class='gsc_row clearfix']/li[1]").text)
    except:
        year.append('-')
    try:
        fuel.append(driver.find_element_by_xpath("//div[@class='gsc_col-xs-12']/ul/li[3]/div/div[2]").text)
    except NoSuchElementException:
        fuel.append(driver.find_element_by_xpath("//ul[@class='gsc_row clearfix']/li[5]").text)
    except:
        fuel.append('-')
    try:
        transmission.append(driver.find_element_by_xpath("//div[@class='gsc_col-xs-12']/ul/li[8]/div/div[2]").text)
    except NoSuchElementException:
        transmission.append(driver.find_element_by_xpath("//ul[@class='gsc_row clearfix']/li[6]").text)
    except:
        transmission.append('-')
    try:
        km.append(driver.find_element_by_xpath("//div[@class='gsc_col-xs-12']/ul/li[4]/div/div[2]").text)
    except NoSuchElementException:
        km.append(driver.find_element_by_xpath("//ul[@class='gsc_row clearfix']/li[3]").text)
    except:
        km.append('-')
    try:
        owners.append(driver.find_element_by_xpath("//div[@class='gsc_col-xs-12']/ul/li[6]/div/div[2]").text)
    except NoSuchElementException:
        owners.append(driver.find_element_by_xpath("//ul[@class='gsc_row clearfix']/li[4]").text)
    except:
        owners.append('-')
        
    location.append("ahmedabad")
    try:
        price.append(driver.find_element_by_xpath("//div[@class='priceSection']").text)
    except NoSuchElementException:
        price.append(driver.find_element_by_xpath("//span[@class='amount']").text)
    except:
        price.append('-')

In [12]:
df=pd.DataFrame({})
df['Brand']=brand
df['model']=model
df['variant']=variant
df['year']=year
df['fuel']=fuel
df['transmission']=transmission
df['km driven']=km
df['No of owners']=owners
df['location']=location
df['price']=price
df

,Brand,model,variant,year,fuel,transmission,km driven,No of owners,location,price
0,2019 Maruti Swift Dzire,2019 Maruti Swift Dzire,VXI 1.2,2019,Petrol,Manual,"9,718 Kms",1st Owner,ahmedabad,"₹ 6,65,000"
1,2012 Maruti Alto K10,2012 Maruti Alto K10,LXI,2012,Petrol,Manual,"89,579 Kms",1st Owner,ahmedabad,"₹ 1,77,500"
2,2016 Maruti Wagon R,2016 Maruti Wagon R,VXI,2016,Petrol,Manual,"81,674 Kms",1st Owner,ahmedabad,"₹ 3,60,000"
3,2011 Honda City,2011 Honda City,1.5 V MT,2011,Petrol,Manual,"38,647 Kms",1st Owner,ahmedabad,"₹ 3,99,500"
4,2016 Nissan Terrano,2016 Nissan Terrano,XL Plus 85 PS,2016,Diesel,Manual,"74,431 Kms",2nd Owner,ahmedabad,"₹ 4,70,500"
...,...,...,...,...,...,...,...,...,...,...
330,2014Honda Amaze SX i-VTEC,2014Honda Amaze SX i-VTEC,2014Honda Amaze SX i-VTEC,2014,Petrol,Manual,"58,000 kms",First Owner,ahmedabad,4.6 Lakh*
331,2016Mahindra Ssangyong Rexton RX7,2016Mahindra Ssangyong Rexton RX7,2016Mahindra Ssangyong Rexton RX7,2016,Diesel,Automatic,"43,000 kms",First Owner,ahmedabad,9 Lakh*
332,2008BMW 5 Series 520d,2008BMW 5 Series 520d,2008BMW 5 Series 520d,2008,Diesel,Automatic,"89,000 kms",Third Owner,ahmedabad,11.5 Lakh*
333,2015Ford EcoSport 1.5 TDCi Titanium BSIV,2015Ford EcoSport 1.5 TDCi Titanium BSIV,2015Ford EcoSport 1.5 TDCi Titanium BSIV,2015,Diesel,Manual,"74,000 kms",First Owner,ahmedabad,5.75 Lakh*
334,2012Toyota Innova 2.5 VX (Diesel) 7 Seater,2012Toyota Innova 2.5 VX (Diesel) 7 Seater,2012Toyota Innova 2.5 VX (Diesel) 7 Seater,2012,Diesel,Manual,"93,000 kms",First Owner,ahmedabad,6.5 Lakh*

In [35]:
df.to_csv("ahmed.csv")

In [36]:
# car search for bangalore
driver = webdriver.Chrome('chromedriver.exe')
driver.get("https://www.cardekho.com/")
driver.get(driver.find_element_by_xpath("//nav[@class='gsc_col-sm-12 gsc_col-md-12']/ul/li[2]/ul/li/ul/li[2]/a").get_attribute("href"))

In [37]:
for i in range(600):
    driver.execute_script("window.scrollBy(0,80)")
    time.sleep(1)

In [38]:
urls=[]
for i in driver.find_elements_by_xpath("//div[@class='gsc_col-xs-7 carsName']/a"):
    urls.append(i.get_attribute("href"))
len(urls)

60

In [39]:
brand=[]
model=[]
variant=[]
year=[]
fuel=[]
transmission=[]
km=[]
owners=[]
location=[]
price=[]

In [40]:
for i in urls:
    driver.get(i)
    time.sleep(1)
    try:
        brand.append(driver.find_element_by_xpath("//div[@class='gsc_col-xs-12']/h1").text)
    except NoSuchElementException:
        brand.append(driver.find_element_by_xpath("//div[@class='vdp-head']").text)
    except:
        brand.append('-')
    try:
        model.append(driver.find_element_by_xpath("//div[@class='gsc_col-xs-12']/h1").text)
    except NoSuchElementException:
        model.append(driver.find_element_by_xpath("//div[@class='vdp-head']").text)
    except:
        model.append('-')
    try:
        variant.append(driver.find_element_by_xpath("//div[@class='variant-name']").text)
    except NoSuchElementException:
        variant.append(driver.find_element_by_xpath("//div[@class='vdp-head']").text)
    except:
        variant.append('-')
    try:
        year.append(driver.find_element_by_xpath("//div[@class='gsc_col-xs-12']/ul/li[1]/div/div[2]").text)
    except NoSuchElementException:
        year.append(driver.find_element_by_xpath("//ul[@class='gsc_row clearfix']/li[1]").text)
    except:
        year.append('-')
    try:
        fuel.append(driver.find_element_by_xpath("//div[@class='gsc_col-xs-12']/ul/li[3]/div/div[2]").text)
    except NoSuchElementException:
        fuel.append(driver.find_element_by_xpath("//ul[@class='gsc_row clearfix']/li[5]").text)
    except:
        fuel.append('-')
    try:
        transmission.append(driver.find_element_by_xpath("//div[@class='gsc_col-xs-12']/ul/li[8]/div/div[2]").text)
    except NoSuchElementException:
        transmission.append(driver.find_element_by_xpath("//ul[@class='gsc_row clearfix']/li[6]").text)
    except:
        transmission.append('-')
    try:
        km.append(driver.find_element_by_xpath("//div[@class='gsc_col-xs-12']/ul/li[4]/div/div[2]").text)
    except NoSuchElementException:
        km.append(driver.find_element_by_xpath("//ul[@class='gsc_row clearfix']/li[3]").text)
    except:
        km.append('-')
    try:
        owners.append(driver.find_element_by_xpath("//div[@class='gsc_col-xs-12']/ul/li[6]/div/div[2]").text)
    except NoSuchElementException:
        owners.append(driver.find_element_by_xpath("//ul[@class='gsc_row clearfix']/li[4]").text)
    except:
        owners.append('-')
        
    location.append("bangalore")
    try:
        price.append(driver.find_element_by_xpath("//div[@class='priceSection']").text)
    except NoSuchElementException:
        price.append(driver.find_element_by_xpath("//span[@class='amount']").text)
    except:
        price.append('-')

In [41]:
df=pd.DataFrame({})
df['Brand']=brand
df['model']=model
df['variant']=variant
df['year']=year
df['fuel']=fuel
df['transmission']=transmission
df['km driven']=km
df['No of owners']=owners
df['location']=location
df['price']=price
df

,Brand,model,variant,year,fuel,transmission,km driven,No of owners,location,price
0,2015 Honda Amaze,2015 Honda Amaze,S i-Vtech,2015,Petrol,Manual,"59,439 Kms",1st Owner,bangalore,"₹ 4,57,500"
1,2018 Renault KWID,2018 Renault KWID,1.0 RXT Optional,2018,Petrol,Manual,"22,912 Kms",1st Owner,bangalore,"₹ 4,44,500"
2,2019 Hyundai Santro,2019 Hyundai Santro,Asta,2019,Petrol,Manual,"19,987 Kms",1st Owner,bangalore,"₹ 5,83,500"
3,2016 Hyundai EON,2016 Hyundai EON,Era Plus,2016,Petrol,Manual,"33,285 Kms",1st Owner,bangalore,"₹ 3,60,000"
4,2014 Ford Ecosport,2014 Ford Ecosport,Titanium Diesel,2014,Diesel,Manual,"62,204 Kms",2nd Owner,bangalore,"₹ 6,22,500"
5,2015 Maruti Wagon R,2015 Maruti Wagon R,VXI BS IV,2015,Petrol,Manual,"31,401 Kms",1st Owner,bangalore,"₹ 4,04,000"
6,2017 Honda Jazz,2017 Honda Jazz,1.2 S i VTEC,2017,Petrol,Manual,"44,490 Kms",1st Owner,bangalore,"₹ 6,51,000"
7,2017 Maruti Vitara Brezza,2017 Maruti Vitara Brezza,VDi,2017,Diesel,Manual,"72,431 Kms",1st Owner,bangalore,"₹ 8,60,000"
8,2017 Ford Figo,2017 Ford Figo,Titanium Diesel,2017,Diesel,Manual,"5,545 Kms",1st Owner,bangalore,"₹ 5,81,000"
9,2015 Tata Zest,2015 Tata Zest,Quadrajet 1.3 XTA,2015,Diesel,Automatic,"53,737 Kms",1st Owner,bangalore,"₹ 4,49,500"
10,2017 Honda Jazz,2017 Honda Jazz,V CVT,2017,Petrol,Automatic,"64,317 Kms",2nd Owner,bangalore,"₹ 6,73,500"
11,2020 MG Hector,2020 MG Hector,Hybrid Sharp MT,2020,Petrol,Manual,"9,097 Kms",1st Owner,bangalore,"₹ 19,03,500"
12,2016 Hyundai Grand i10,2016 Hyundai Grand i10,CRDi Asta Option,2016,Diesel,Manual,"23,622 Kms",1st Owner,bangalore,"₹ 6,03,000"
13,2021 Hyundai i20,2021 Hyundai i20,Sportz Diesel,2021,Diesel,Manual,"9,593 Kms",1st Owner,bangalore,"₹ 9,94,000"
14,2013Honda CR V 2.4L 4WD AT AVN,2013Honda CR V 2.4L 4WD AT AVN,2013Honda CR V 2.4L 4WD AT AVN,2013,Petrol,Automatic,"95,000 kms",First Owner,bangalore,10 Lakh*
15,2018Lexus NX 300h,2018Lexus NX 300h,2018Lexus NX 300h,2018,Petrol,Automatic,"7,622 kms",First Owner,bangalore,63.95 Lakh*
16,2010Audi Q5 3.0 TDI,2010Audi Q5 3.0 TDI,2010Audi Q5 3.0 TDI,2010,Diesel,Automatic,"80,000 kms",First Owner,bangalore,12.5 Lakh*
17,2013Audi Q3 2.0 TDI,2013Audi Q3 2.0 TDI,2013Audi Q3 2.0 TDI,2013,Diesel,Automatic,"67,000 kms",Third Owner,bangalore,13.5 Lakh*
18,2009Honda City 1.5 V AT,2009Honda City 1.5 V AT,2009Honda City 1.5 V AT,2009,Petrol,Automatic,"45,000 kms",Second Owner,bangalore,4.45 Lakh*
19,2015BMW 3 Series 320d Sport Line,2015BMW 3 Series 320d Sport Line,2015BMW 3 Series 320d Sport Line,2015,Diesel,Automatic,"64,000 kms",First Owner,bangalore,22.75 Lakh*
20,2015 Hyundai EON,2015 Hyundai EON,Magna Plus,2015,Petrol,Manual,"4,924 Kms",1st Owner,bangalore,"₹ 3,47,500"
21,2016 Hyundai Grand i10,2016 Hyundai Grand i10,Sportz,2016,Petrol,Manual,"18,740 Kms",1st Owner,bangalore,"₹ 5,26,500"
22,2018 Maruti Alto 800,2018 Maruti Alto 800,LXI,2017,Petrol,Manual,"42,752 Kms",1st Owner,bangalore,"₹ 3,57,000"
23,2016 Maruti Celerio,2016 Maruti Celerio,VXI AT,2016,Petrol,Automatic,"26,832 Kms",1st Owner,bangalore,"₹ 4,86,326"
24,2018 Maruti Ignis,2018 Maruti Ignis,1.2 Delta BSIV,2017,Petrol,Manual,"42,206 Kms",1st Owner,bangalore,"₹ 5,32,000"
25,2017 Hyundai Grand i10,2017 Hyundai Grand i10,Sportz,2017,Petrol,Manual,"49,814 Kms",1st Owner,bangalore,"₹ 5,10,000"
26,2018 Maruti Celerio,2018 Maruti Celerio,VXI,2018,Petrol,Manual,"5,671 Kms",1st Owner,bangalore,"₹ 5,51,372"
27,2019 Hyundai Grand i10,2019 Hyundai Grand i10,Sportz,2019,Petrol,Manual,"7,129 Kms",1st Owner,bangalore,"₹ 6,36,500"
28,2018 Renault KWID,2018 Renault KWID,Climber 1.0 AMT BSIV,2018,Petrol,Automatic,"12,297 Kms",1st Owner,bangalore,"₹ 4,78,000"
29,2018 Renault KWID,2018 Renault KWID,1.0 RXT 02 Anniversary Edition,2018,Petrol,Manual,"17,873 Kms",1st Owner,bangalore,"₹ 4,39,885"
30,2017 Maruti Wagon R,2017 Maruti Wagon R,VXI,2017,Petrol,Manual,"18,900 Kms",1st Owner,bangalore,"₹ 4,91,500"
31,2015 Hyundai Grand i10,2015 Hyundai Grand i10,Sportz,2014,Petrol,Manual,"30,607 Kms",1st Owner,bangalore,"₹ 4,78,500"
32,2016 Hyundai Grand i10,2016 Hyundai Grand i10,1.2 Kappa Magna AT,2016,Petrol,Automatic,"19,255 Kms",2nd Owner,bangalore,"₹ 5,04,500"
33,2017 Renault KWID,2017 Renault KWID,1.0 RXT AMT,2017,Petrol,Automatic,"10,003 Kms",1st Owner,bangalore,"₹ 4,46,000"
34,2014 Maruti Celerio,2014 Maruti Celerio,VXI,2014,Petrol,Manual,"37,952 Kms",1st Owner,bangalore,"₹ 3,88,500"
35,2016 Honda Jazz,2016 Honda Jazz,V CVT,2016,Petrol,KA50,"37,789 Kms",2nd Owner,bangalore,"₹ 6,09,000"
36,2018 Renault KWID,2018 Renault KWID,AMT,2018,Petrol,Automatic,"20,965 Kms",1st Owner,bangalore,"₹ 4,67,000"
37,2016 Hyundai Grand i10,2016 Hyundai Grand i10,Sportz,2016,Petrol,Manual,"28,974 Kms",1st Owner,bangalore,"₹ 5,16,000"
38,2018 Tata Tigor,2018 Tata Tigor,1.2 Revotron XZA,2018,Petrol,Automatic,"11,846 Kms",1st Owner,bangalore,"₹ 6,18,500"
39,2018 Maruti Celerio,2018 Maruti Celerio,ZXI,2018,Petrol,Manual,"17,247 Kms",1st Owner,bangalore,"₹ 5,16,000"
40,2015 Hyundai Grand i10,2015 Hyundai Grand i10,AT Asta,2015,Petrol,Automatic,"26,776 Kms",2nd Owner,bangalore,"₹ 5,15,500"
41,2011 Maruti Swift Dzire,2011 Maruti Swift Dzire,VXI,2011,Petrol,Manual,"73,991 Kms",1st Owner,bangalore,"₹ 3,94,000"
42,2017 Hyundai Grand i10,2017 Hyundai Grand i10,1.2 Kappa Asta,2017,Petrol,Manual,"41,894 Kms",1st Owner,bangalore,"₹ 5,72,500"
43,2009 Maruti Wagon R,2009 Maruti Wagon R,VXI Minor,2009,Petrol,Manual,"51,606 Kms",1st Owner,bangalore,"₹ 3,08,000"
44,2015 Hyundai Grand i10,2015 Hyundai Grand i10,Asta,2015,Petrol,Manual,"13,179 Kms",1st Owner,bangalore,"₹ 5,28,500"
45,2012 Skoda New Laura,2012 Skoda New Laura,Ambiente 2.0 TDI CR MT,2011,Diesel,Manual,"81,309 Kms",2nd Owner,bangalore,"₹ 4,61,970"
46,2018 Renault KWID,2018 Renault KWID,Climber 1.0 AMT Opt,2018,Petrol,Automatic,"17,000 Kms",1st Owner,bangalore,"₹ 4,99,568"
47,2016 Maruti Swift,2016 Maruti Swift,VXI Optional,2016,Petrol,Manual,"37,997 Kms",2nd Owner,bangalore,"₹ 5,71,000"
48,2018 Renault KWID,2018 Renault KWID,RXL,2018,Petrol,Manual,"41,377 Kms",1st Owner,bangalore,"₹ 3,90,120"
49,2008 Hyundai i10,2008 Hyundai i10,Magna 1.1,2008,Petrol,Manual,"43,582 Kms",2nd Owner,bangalore,"₹ 2,41,000"
50,2013 Hyundai Grand i10,2013 Hyundai Grand i10,1.2 Kappa Asta,2013,Petrol,Manual,"44,110 Kms",1st Owner,bangalore,"₹ 4,52,760"
51,2017 Maruti Wagon R,2017 Maruti Wagon R,VXI BS IV,2017,Petrol,Manual,"28,512 Kms",2nd Owner,bangalore,"₹ 4,62,500"
52,2017 Renault KWID,2017 Renault KWID,1.0 RXT Opt,2017,Petrol,Manual,"23,390 Kms",1st Owner,bangalore,"₹ 4,58,532"
53,2016 Renault KWID,2016 Renault KWID,1.0 RXT AMT,2016,Petrol,Automatic,"45,115 Kms",1st Owner,bangalore,"₹ 3,87,500"
54,2015 Honda Jazz,2015 Honda Jazz,1.2 SV i VTEC,2015,Petrol,Manual,"26,166 Kms",1st Owner,bangalore,"₹ 6,11,871"
55,2017 Maruti Wagon R,2017 Maruti Wagon R,VXI Plus Optional,2017,Petrol,Manual,"30,393 Kms",1st Owner,bangalore,"₹ 4,67,000"
56,2016 Maruti Baleno,2016 Maruti Baleno,Delta,2016,Petrol,Manual,"36,638 Kms",1st Owner,bangalore,"₹ 5,85,000"
57,2016 Renault KWID,2016 Renault KWID,RXT,2016,Petrol,Manual,"32,850 Kms",1st Owner,bangalore,"₹ 3,62,000"
58,2017 Maruti Swift,2017 Maruti Swift,VXI,2017,Petrol,Manual,"40,231 Kms",1st Owner,bangalore,"₹ 5,79,500"
59,2015 Honda Jazz,2015 Honda Jazz,V,2015,Petrol,Manual,"41,605 Kms",2nd Owner,bangalore,"₹ 5,50,000"

In [43]:
df.to_csv("bangalore.csv")

In [44]:
# car search for chennai
driver.get(driver.find_element_by_xpath("//nav[@class='gsc_col-sm-12 gsc_col-md-12']/ul/li[2]/ul/li/ul/li[3]/a").get_attribute("href"))

In [45]:
for i in range(600):
    driver.execute_script("window.scrollBy(0,100)")
    time.sleep(1)

In [46]:
urls=[]
for i in driver.find_elements_by_xpath("//div[@class='gsc_col-xs-7 carsName']/a"):
    urls.append(i.get_attribute("href"))
len(urls)

60

In [47]:
brand=[]
model=[]
variant=[]
year=[]
fuel=[]
transmission=[]
km=[]
owners=[]
location=[]
price=[]


for i in urls:
    driver.get(i)
    time.sleep(3)
    try:
        brand.append(driver.find_element_by_xpath("//div[@class='gsc_col-xs-12']/h1").text)
    except NoSuchElementException:
        brand.append(driver.find_element_by_xpath("//div[@class='vdp-head']").text)
    except:
        brand.append('-')
    try:
        model.append(driver.find_element_by_xpath("//div[@class='gsc_col-xs-12']/h1").text)
    except NoSuchElementException:
        model.append(driver.find_element_by_xpath("//div[@class='vdp-head']").text)
    except:
        model.append('-')
    try:
        variant.append(driver.find_element_by_xpath("//div[@class='variant-name']").text)
    except NoSuchElementException:
        variant.append(driver.find_element_by_xpath("//div[@class='vdp-head']").text)
    except:
        variant.append('-')
    try:
        year.append(driver.find_element_by_xpath("//div[@class='gsc_col-xs-12']/ul/li[1]/div/div[2]").text)
    except NoSuchElementException:
        year.append(driver.find_element_by_xpath("//ul[@class='gsc_row clearfix']/li[1]").text)
    except:
        year.append('-')
    try:
        fuel.append(driver.find_element_by_xpath("//div[@class='gsc_col-xs-12']/ul/li[3]/div/div[2]").text)
    except NoSuchElementException:
        fuel.append(driver.find_element_by_xpath("//ul[@class='gsc_row clearfix']/li[5]").text)
    except:
        fuel.append('-')
    try:
        transmission.append(driver.find_element_by_xpath("//div[@class='gsc_col-xs-12']/ul/li[8]/div/div[2]").text)
    except NoSuchElementException:
        transmission.append(driver.find_element_by_xpath("//ul[@class='gsc_row clearfix']/li[6]").text)
    except:
        transmission.append('-')
    try:
        km.append(driver.find_element_by_xpath("//div[@class='gsc_col-xs-12']/ul/li[4]/div/div[2]").text)
    except NoSuchElementException:
        km.append(driver.find_element_by_xpath("//ul[@class='gsc_row clearfix']/li[3]").text)
    except:
        km.append('-')
    try:
        owners.append(driver.find_element_by_xpath("//div[@class='gsc_col-xs-12']/ul/li[6]/div/div[2]").text)
    except NoSuchElementException:
        owners.append(driver.find_element_by_xpath("//ul[@class='gsc_row clearfix']/li[4]").text)
    except:
        owners.append('-')
        
    location.append("chennai")
    try:
        price.append(driver.find_element_by_xpath("//div[@class='priceSection']").text)
    except NoSuchElementException:
        price.append(driver.find_element_by_xpath("//span[@class='amount']").text)
    except:
        price.append('-')

In [48]:
df=pd.DataFrame({})
df['Brand']=brand
df['model']=model
df['variant']=variant
df['year']=year
df['fuel']=fuel
df['transmission']=transmission
df['km driven']=km
df['No of owners']=owners
df['location']=location
df['price']=price
df

,Brand,model,variant,year,fuel,transmission,km driven,No of owners,location,price
0,2016Hyundai Creta 1.6 CRDi SX Plus,2016Hyundai Creta 1.6 CRDi SX Plus,2016Hyundai Creta 1.6 CRDi SX Plus,2016,Diesel,Manual,"1,00,000 kms",First Owner,chennai,9 Lakh*
1,2016Datsun GO A EPS,2016Datsun GO A EPS,2016Datsun GO A EPS,2016,Petrol,Manual,"24,000 kms",First Owner,chennai,3.35 Lakh*
2,2015Hyundai Grand i10 Asta,2015Hyundai Grand i10 Asta,2015Hyundai Grand i10 Asta,2015,Petrol,Manual,"43,000 kms",First Owner,chennai,4.9 Lakh*
3,2016Hyundai i20 2015-2017 Asta 1.2,2016Hyundai i20 2015-2017 Asta 1.2,2016Hyundai i20 2015-2017 Asta 1.2,2016,Petrol,Manual,"54,850 kms",First Owner,chennai,6.1 Lakh*
4,2016Honda Jazz 1.2 SV i VTEC,2016Honda Jazz 1.2 SV i VTEC,2016Honda Jazz 1.2 SV i VTEC,2016,Petrol,Manual,"34,000 kms",First Owner,chennai,5.75 Lakh*
5,2015Land Rover Range Rover Evoque HSE Dynamic,2015Land Rover Range Rover Evoque HSE Dynamic,2015Land Rover Range Rover Evoque HSE Dynamic,2015,Diesel,Automatic,"42,000 kms",First Owner,chennai,32 Lakh*
6,2011Maruti Alto K10 2010-2014 VXI,2011Maruti Alto K10 2010-2014 VXI,2011Maruti Alto K10 2010-2014 VXI,2011,Petrol,Manual,"42,364 kms",Second Owner,chennai,2.25 Lakh*
7,2008Hyundai i10 Era,2008Hyundai i10 Era,2008Hyundai i10 Era,2008,Petrol,Manual,"78,000 kms",Second Owner,chennai,2.25 Lakh*
8,2017Maruti Swift ZDI BSIV,2017Maruti Swift ZDI BSIV,2017Maruti Swift ZDI BSIV,2017,Diesel,Manual,"81,000 kms",First Owner,chennai,6.25 Lakh*
9,2018Honda WR-V i-VTEC VX,2018Honda WR-V i-VTEC VX,2018Honda WR-V i-VTEC VX,2018,Petrol,Manual,"17,000 kms",First Owner,chennai,8.75 Lakh*
10,2013Ford Figo Petrol EXI,2013Ford Figo Petrol EXI,2013Ford Figo Petrol EXI,2013,Petrol,Manual,"32,000 kms",First Owner,chennai,2.95 Lakh*
11,2019Renault Duster 85PS Diesel RxS,2019Renault Duster 85PS Diesel RxS,2019Renault Duster 85PS Diesel RxS,2019,Diesel,Manual,"16,000 kms",First Owner,chennai,10.9 Lakh*
12,2000Hyundai Santro LE zipPlus,2000Hyundai Santro LE zipPlus,2000Hyundai Santro LE zipPlus,2000,Petrol,Manual,"68,000 kms",Second Owner,chennai,"65,000*"
13,2016Toyota Innova Crysta 2016-2020 2.4 ZX MT,2016Toyota Innova Crysta 2016-2020 2.4 ZX MT,2016Toyota Innova Crysta 2016-2020 2.4 ZX MT,2016,Diesel,Manual,"1,08,666 kms",First Owner,chennai,16.8 Lakh*
14,2018Maruti Baleno Zeta 1.2,2018Maruti Baleno Zeta 1.2,2018Maruti Baleno Zeta 1.2,2018,Petrol,Manual,"34,000 kms",First Owner,chennai,6.9 Lakh*
15,2018Ford EcoSport 1.5 Petrol Titanium Plus AT,2018Ford EcoSport 1.5 Petrol Titanium Plus AT,2018Ford EcoSport 1.5 Petrol Titanium Plus AT,2018,Petrol,Automatic,"14,203 kms",First Owner,chennai,9.7 Lakh*
16,2014Hyundai Verna 1.6 SX,2014Hyundai Verna 1.6 SX,2014Hyundai Verna 1.6 SX,2014,Diesel,Manual,"61,000 kms",Second Owner,chennai,6.5 Lakh*
17,2016Hyundai Grand i10 Asta,2016Hyundai Grand i10 Asta,2016Hyundai Grand i10 Asta,2016,Petrol,Manual,"43,000 kms",Second Owner,chennai,4.65 Lakh*
18,2020Toyota Innova Crysta 2016-2020 2.4 ZX AT,2020Toyota Innova Crysta 2016-2020 2.4 ZX AT,2020Toyota Innova Crysta 2016-2020 2.4 ZX AT,2020,Diesel,Automatic,"2,500 kms",First Owner,chennai,28 Lakh*
19,2017Honda WR-V Exclusive Petrol,2017Honda WR-V Exclusive Petrol,2017Honda WR-V Exclusive Petrol,2017,Petrol,Manual,"17,603 kms",First Owner,chennai,7.5 Lakh*
20,2011Hyundai i20 1.2 Sportz,2011Hyundai i20 1.2 Sportz,2011Hyundai i20 1.2 Sportz,2011,Petrol,Manual,"60,000 kms",Second Owner,chennai,3.4 Lakh*
21,2016Hyundai Creta 1.6 CRDi SX,2016Hyundai Creta 1.6 CRDi SX,2016Hyundai Creta 1.6 CRDi SX,2016,Diesel,Manual,"69,000 kms",First Owner,chennai,10.9 Lakh*
22,2013Fiat Grande Punto 1.3 Dynamic (Diesel),2013Fiat Grande Punto 1.3 Dynamic (Diesel),2013Fiat Grande Punto 1.3 Dynamic (Diesel),2013,Diesel,Manual,"68,803 kms",First Owner,chennai,3.5 Lakh*
23,2017Maruti Ciaz 1.4 Alpha,2017Maruti Ciaz 1.4 Alpha,2017Maruti Ciaz 1.4 Alpha,2017,Petrol,Manual,"34,000 kms",First Owner,chennai,8 Lakh*
24,2016Honda City i VTEC V,2016Honda City i VTEC V,2016Honda City i VTEC V,2016,Petrol,Manual,"32,000 kms",First Owner,chennai,8.15 Lakh*
25,2019Honda Jazz 1.2 VX i VTEC,2019Honda Jazz 1.2 VX i VTEC,2019Honda Jazz 1.2 VX i VTEC,2019,Petrol,Manual,"1,600 kms",First Owner,chennai,8.25 Lakh*
26,2018Honda Jazz V Diesel,2018Honda Jazz V Diesel,2018Honda Jazz V Diesel,2018,Diesel,Manual,"29,055 kms",First Owner,chennai,7.5 Lakh*
27,2012Volkswagen Vento Diesel Highline,2012Volkswagen Vento Diesel Highline,2012Volkswagen Vento Diesel Highline,2012,Diesel,Manual,"49,000 kms",First Owner,chennai,5.65 Lakh*
28,2012Hyundai Santa Fe 4X2,2012Hyundai Santa Fe 4X2,2012Hyundai Santa Fe 4X2,2012,Diesel,Manual,"1,03,000 kms",First Owner,chennai,6.7 Lakh*
29,2012Jaguar XF 3.0 Litre S Premium Luxury,2012Jaguar XF 3.0 Litre S Premium Luxury,2012Jaguar XF 3.0 Litre S Premium Luxury,2012,Diesel,Automatic,"59,000 kms",Second Owner,chennai,21 Lakh*
30,2016Honda Jazz 1.2 V AT i VTEC,2016Honda Jazz 1.2 V AT i VTEC,2016Honda Jazz 1.2 V AT i VTEC,2016,Petrol,Automatic,"45,000 kms",First Owner,chennai,6.9 Lakh*
31,2014Hyundai EON Era Plus,2014Hyundai EON Era Plus,2014Hyundai EON Era Plus,2014,Petrol,Manual,"38,000 kms",First Owner,chennai,3.35 Lakh*
32,2018New Skoda Rapid 1.0 TSI Ambition AT,2018New Skoda Rapid 1.0 TSI Ambition AT,2018New Skoda Rapid 1.0 TSI Ambition AT,2018,Petrol,Automatic,"13,500 kms",First Owner,chennai,9.9 Lakh*
33,2014Maruti Swift Dzire VXI,2014Maruti Swift Dzire VXI,2014Maruti Swift Dzire VXI,2014,Petrol,Manual,"25,000 kms",First Owner,chennai,5 Lakh*
34,2019Hyundai Grand i10 1.2 Kappa Sportz BSIV,2019Hyundai Grand i10 1.2 Kappa Sportz BSIV,2019Hyundai Grand i10 1.2 Kappa Sportz BSIV,2019,Petrol,Manual,"15,000 kms",First Owner,chennai,5.75 Lakh*
35,2016Maruti Baleno Delta 1.2,2016Maruti Baleno Delta 1.2,2016Maruti Baleno Delta 1.2,2016,Petrol,Manual,"54,000 kms",First Owner,chennai,6.1 Lakh*
36,2014Ford EcoSport 1.5 DV5 MT Titanium,2014Ford EcoSport 1.5 DV5 MT Titanium,2014Ford EcoSport 1.5 DV5 MT Titanium,2014,Diesel,Manual,"58,000 kms",Second Owner,chennai,6.35 Lakh*
37,2017Honda WR-V i-DTEC VX,2017Honda WR-V i-DTEC VX,2017Honda WR-V i-DTEC VX,2017,Diesel,Manual,"43,000 kms",First Owner,chennai,8.75 Lakh*
38,2013Toyota Corolla Altis D-4D G,2013Toyota Corolla Altis D-4D G,2013Toyota Corolla Altis D-4D G,2013,Diesel,Manual,"1,50,000 kms",First Owner,chennai,6.5 Lakh*
39,2015Maruti Swift VDI,2015Maruti Swift VDI,2015Maruti Swift VDI,2015,Diesel,Manual,"76,000 kms",First Owner,chennai,5.4 Lakh*
40,2010Toyota Fortuner 3.0 Diesel,2010Toyota Fortuner 3.0 Diesel,2010Toyota Fortuner 3.0 Diesel,2010,Diesel,Manual,"1,85,000 kms",First Owner,chennai,11.25 Lakh*
41,2018Hyundai Creta 1.6 EX Petrol,2018Hyundai Creta 1.6 EX Petrol,2018Hyundai Creta 1.6 EX Petrol,2018,Petrol,Manual,"39,000 kms",First Owner,chennai,8.6 Lakh*
42,2016Maruti Swift Dzire AMT ZDI,2016Maruti Swift Dzire AMT ZDI,2016Maruti Swift Dzire AMT ZDI,2016,Diesel,Automatic,"75,000 kms",First Owner,chennai,5.9 Lakh*
43,2017Hyundai Creta 1.6 CRDi SX Plus,2017Hyundai Creta 1.6 CRDi SX Plus,2017Hyundai Creta 1.6 CRDi SX Plus,2017,Diesel,Manual,"66,000 kms",First Owner,chennai,11.5 Lakh*
44,2011Skoda Superb 2.8 V6 AT,2011Skoda Superb 2.8 V6 AT,2011Skoda Superb 2.8 V6 AT,2011,Petrol,Automatic,"1,28,000 kms",First Owner,chennai,6.5 Lakh*
45,2019Renault Triber RXT,2019Renault Triber RXT,2019Renault Triber RXT,2019,Petrol,Manual,"24,000 kms",First Owner,chennai,6.5 Lakh*
46,2015Maruti Alto 800 LXI,2015Maruti Alto 800 LXI,2015Maruti Alto 800 LXI,2015,Petrol,Manual,"51,000 kms",First Owner,chennai,2.9 Lakh*
47,2016Honda Amaze 2016-2021 SX i DTEC,2016Honda Amaze 2016-2021 SX i DTEC,2016Honda Amaze 2016-2021 SX i DTEC,2016,Diesel,Manual,"27,000 kms",First Owner,chennai,6.5 Lakh*
48,2016Maruti Ertiga ZXI Plus,2016Maruti Ertiga ZXI Plus,2016Maruti Ertiga ZXI Plus,2016,Petrol,Manual,"27,000 kms",First Owner,chennai,7.3 Lakh*
49,2014Honda City i VTEC V,2014Honda City i VTEC V,2014Honda City i VTEC V,2014,Petrol,Manual,"94,014 kms",Second Owner,chennai,5.4 Lakh*
50,2017Honda Amaze 2016-2021 S i-VTEC,2017Honda Amaze 2016-2021 S i-VTEC,2017Honda Amaze 2016-2021 S i-VTEC,2017,Petrol,Manual,"31,000 kms",First Owner,chennai,6 Lakh*
51,2011Hyundai Verna Transform SX VGT CRDi,2011Hyundai Verna Transform SX VGT CRDi,2011Hyundai Verna Transform SX VGT CRDi,2011,Diesel,Manual,"79,000 kms",First Owner,chennai,3.49 Lakh*
52,2017Toyota Fortuner 2016-2021 2.8 2WD MT BSIV,2017Toyota Fortuner 2016-2021 2.8 2WD MT BSIV,2017Toyota Fortuner 2016-2021 2.8 2WD MT BSIV,2017,Diesel,Manual,"72,000 kms",First Owner,chennai,26.98 Lakh*
53,2013Fiat Linea Emotion Pack,2013Fiat Linea Emotion Pack,2013Fiat Linea Emotion Pack,2013,Petrol,Manual,"27,650 kms",First Owner,chennai,3.25 Lakh*
54,2012Ford Fiesta 1.5 TDCi Titanium,2012Ford Fiesta 1.5 TDCi Titanium,2012Ford Fiesta 1.5 TDCi Titanium,2012,Diesel,Manual,"78,900 kms",First Owner,chennai,3.6 Lakh*
55,2014Volkswagen Polo 1.2 MPI Comfortline,2014Volkswagen Polo 1.2 MPI Comfortline,2014Volkswagen Polo 1.2 MPI Comfortline,2014,Petrol,Manual,"65,000 kms",First Owner,chennai,4.75 Lakh*
56,2009Honda City 1.5 S MT,2009Honda City 1.5 S MT,2009Honda City 1.5 S MT,2009,Petrol,Manual,"76,165 kms",Second Owner,chennai,3.6 Lakh*
57,2007Maruti Esteem Vxi - BSIII,2007Maruti Esteem Vxi - BSIII,2007Maruti Esteem Vxi - BSIII,2007,Petrol,Manual,"65,000 kms",Second Owner,chennai,1.4 Lakh*
58,2017Ford Endeavour 3.2 Trend AT 4X4,2017Ford Endeavour 3.2 Trend AT 4X4,2017Ford Endeavour 3.2 Trend AT 4X4,2017,Diesel,Automatic,"60,000 kms",First Owner,chennai,23 Lakh*
59,2017Ford EcoSport 1.0 Ecoboost Titanium Plus BSIV,2017Ford EcoSport 1.0 Ecoboost Titanium Plus BSIV,2017Ford EcoSport 1.0 Ecoboost Titanium Plus BSIV,2017,Petrol,Manual,"17,000 kms",First Owner,chennai,7.2 Lakh*

In [50]:
df.to_csv("chennai.csv")

In [51]:
driver = webdriver.Chrome('chromedriver.exe')
driver.get("https://www.cardekho.com/")

In [52]:
# car search for kolkata
driver.get(driver.find_element_by_xpath("//nav[@class='gsc_col-sm-12 gsc_col-md-12']/ul/li[2]/ul/li/ul/li[7]/a").get_attribute("href"))

In [53]:
for i in range(600):
    driver.execute_script("window.scrollBy(0,110)")
    time.sleep(1)

In [54]:
urls=[]
for i in driver.find_elements_by_xpath("//div[@class='gsc_col-xs-7 carsName']/a"):
    urls.append(i.get_attribute("href"))

In [55]:
len(urls)

100

In [56]:
brand=[]
model=[]
variant=[]
year=[]
fuel=[]
transmission=[]
km=[]
owners=[]
location=[]
price=[]


for i in urls:
    driver.get(i)
    time.sleep(3)
    try:
        brand.append(driver.find_element_by_xpath("//div[@class='gsc_col-xs-12']/h1").text)
    except NoSuchElementException:
        brand.append(driver.find_element_by_xpath("//div[@class='vdp-head']").text)
    except:
        brand.append('-')
    try:
        model.append(driver.find_element_by_xpath("//div[@class='gsc_col-xs-12']/h1").text)
    except NoSuchElementException:
        model.append(driver.find_element_by_xpath("//div[@class='vdp-head']").text)
    except:
        model.append('-')
    try:
        variant.append(driver.find_element_by_xpath("//div[@class='variant-name']").text)
    except NoSuchElementException:
        variant.append(driver.find_element_by_xpath("//div[@class='vdp-head']").text)
    except :
        variant.append('-')
    try:
        year.append(driver.find_element_by_xpath("//div[@class='gsc_col-xs-12']/ul/li[1]/div/div[2]").text)
    except NoSuchElementException:
        year.append(driver.find_element_by_xpath("//ul[@class='gsc_row clearfix']/li[1]").text)
    except :
        year.append('-')
    try:
        fuel.append(driver.find_element_by_xpath("//div[@class='gsc_col-xs-12']/ul/li[3]/div/div[2]").text)
    except NoSuchElementException:
        fuel.append(driver.find_element_by_xpath("//ul[@class='gsc_row clearfix']/li[5]").text)
    except :
        fuel.append('-')
    try:
        transmission.append(driver.find_element_by_xpath("//div[@class='gsc_col-xs-12']/ul/li[8]/div/div[2]").text)
    except NoSuchElementException :
        transmission.append(driver.find_element_by_xpath("//ul[@class='gsc_row clearfix']/li[6]").text)
    except:
        transmission.append('-')
    try:
        km.append(driver.find_element_by_xpath("//div[@class='gsc_col-xs-12']/ul/li[4]/div/div[2]").text)
    except NoSuchElementException:
        km.append(driver.find_element_by_xpath("//ul[@class='gsc_row clearfix']/li[3]").text)
    except:
        km.append('-')
    try:
        owners.append(driver.find_element_by_xpath("//div[@class='gsc_col-xs-12']/ul/li[6]/div/div[2]").text)
    except NoSuchElementException:
        owners.append(driver.find_element_by_xpath("//ul[@class='gsc_row clearfix']/li[4]").text)
    except:
        owners.append('-')
        
    location.append("kolkata")
    try:
        price.append(driver.find_element_by_xpath("//div[@class='priceSection']").text)
    except NoSuchElementException:
        price.append(driver.find_element_by_xpath("//span[@class='amount']").text)
    except:
        price.append('-')

In [57]:
df=pd.DataFrame({})
df['Brand']=brand
df['model']=model
df['variant']=variant
df['year']=year
df['fuel']=fuel
df['transmission']=transmission
df['km driven']=km
df['No of owners']=owners
df['location']=location
df['price']=price
df

,Brand,model,variant,year,fuel,transmission,km driven,No of owners,location,price
0,2010Volkswagen Passat 1.8 TSI MT,2010Volkswagen Passat 1.8 TSI MT,2010Volkswagen Passat 1.8 TSI MT,2010,Petrol,Manual,"43,000 kms",First Owner,kolkata,4.7 Lakh*
1,2018Maruti Celerio VXI AMT BSIV,2018Maruti Celerio VXI AMT BSIV,2018Maruti Celerio VXI AMT BSIV,2018,Petrol,Automatic,"11,519 kms",First Owner,kolkata,4.65 Lakh*
2,2016Maruti Alto K10 VXI,2016Maruti Alto K10 VXI,2016Maruti Alto K10 VXI,2016,Petrol,Manual,"37,282 kms",First Owner,kolkata,2.85 Lakh*
3,2015Hyundai i20 Magna 1.2,2015Hyundai i20 Magna 1.2,2015Hyundai i20 Magna 1.2,2015,Petrol,Manual,"41,000 kms",Second Owner,kolkata,4.45 Lakh*
4,2013Toyota Etios G,2013Toyota Etios G,2013Toyota Etios G,2013,Petrol,Manual,"35,500 kms",Second Owner,kolkata,2.25 Lakh*
...,...,...,...,...,...,...,...,...,...,...
95,2015Mahindra Bolero 2011-2019 SLX,2015Mahindra Bolero 2011-2019 SLX,2015Mahindra Bolero 2011-2019 SLX,2015,Diesel,Manual,"1,39,139 kms",First Owner,kolkata,4.75 Lakh*
96,2016Maruti Swift LDI BSIV,2016Maruti Swift LDI BSIV,2016Maruti Swift LDI BSIV,2016,Diesel,Manual,"1,30,130 kms",First Owner,kolkata,3.95 Lakh*
97,2016Toyota Innova Crysta 2016-2020 2.4 ZX MT BSIV,2016Toyota Innova Crysta 2016-2020 2.4 ZX MT BSIV,2016Toyota Innova Crysta 2016-2020 2.4 ZX MT BSIV,2016,Diesel,Manual,"35,000 kms",First Owner,kolkata,16.75 Lakh*
98,2015Honda City i VTEC SV,2015Honda City i VTEC SV,2015Honda City i VTEC SV,2015,Petrol,Manual,"34,295 kms",First Owner,kolkata,5.65 Lakh*
99,2016Volkswagen Ameo 1.2 MPI Highline,2016Volkswagen Ameo 1.2 MPI Highline,2016Volkswagen Ameo 1.2 MPI Highline,2016,Petrol,Manual,"32,000 kms",First Owner,kolkata,4.75 Lakh*

In [59]:
df.to_csv("kolkata.csv")

In [25]:
# car search for pune
driver.get(driver.find_element_by_xpath("//nav[@class='gsc_col-sm-12 gsc_col-md-12']/ul/li[2]/ul/li/ul/li[9]/a").get_attribute("href"))

In [26]:
for i in range(1000):
    driver.execute_script("window.scrollBy(0,110)")
    time.sleep(2)

In [27]:
urls=[]
for i in driver.find_elements_by_xpath("//div[@class='gsc_col-xs-7 carsName']/a"):
    urls.append(i.get_attribute("href"))

In [28]:
len(urls)

60

In [29]:
brand=[]
model=[]
variant=[]
year=[]
fuel=[]
transmission=[]
km=[]
owners=[]
location=[]
price=[]


for i in urls:
    driver.get(i)
    time.sleep(3)
    try:
        brand.append(driver.find_element_by_xpath("/html/body/div[2]/div/div[1]/div/div/main/div/div/div[2]/div[1]/div/div/div/div[1]/div[1]/h1").text)
    except NoSuchElementException:
        brand.append('-')
    try:
        model.append(driver.find_element_by_xpath("/html/body/div[2]/div/div[1]/div/div/main/div/div/div[2]/div[1]/div/div/div/div[1]/div[1]/h1").text)
    except NoSuchElementException:
        model.append('-')
    try:
        variant.append(driver.find_element_by_xpath("/html/body/div[2]/div/div[1]/div/div/main/div/div/div[2]/div[1]/div/div/div/div[1]/div[1]/h1").text)
    except NoSuchElementException:
        variant.append('-')
    try:
        year.append(driver.find_element_by_xpath("/html/body/div[2]/div/div[1]/div/div/main/div/div/div[1]/div[3]/div/div/div/ul/li[1]/div/div[2]").text)
    except NoSuchElementException:
        year.append('-')
    try:
        fuel.append(driver.find_element_by_xpath("/html/body/div[2]/div/div[1]/div/div/main/div/div/div[1]/div[3]/div/div/div/ul/li[3]/div/div[2]").text)
    except NoSuchElementException:
        fuel.append('-')
    try:
        transmission.append(driver.find_element_by_xpath("/html/body/div[2]/div/div[1]/div/div/main/div/div/div[1]/div[3]/div/div/div/ul/li[8]/div/div[2]").text)
    except NoSuchElementException:
        transmission.append('-')
    try:
        km.append(driver.find_element_by_xpath("/html/body/div[2]/div/div[1]/div/div/main/div/div/div[1]/div[3]/div/div/div/ul/li[4]/div/div[2]").text)
    except NoSuchElementException:
        km.append('-')
    try:
        owners.append(driver.find_element_by_xpath("/html/body/div[2]/div/div[1]/div/div/main/div/div/div[1]/div[3]/div/div/div/ul/li[6]/div/div[2]").text)
    except NoSuchElementException:
        owners.append('-')
        
    location.append("Pune")
    try:
        price.append(driver.find_element_by_xpath("//div[@class='priceSection']").text)
    except NoSuchElementException:
        price.append('-')

In [30]:
df=pd.DataFrame({})
df['Brand']=brand
df['model']=model
df['variant']=variant
df['year']=year
df['fuel']=fuel
df['transmission']=transmission
df['km driven']=km
df['No of owners']=owners
df['location']=location
df['price']=price
df

,Brand,model,variant,year,fuel,transmission,km driven,No of owners,location,price
0,2019 Maruti Vitara Brezza,2019 Maruti Vitara Brezza,2019 Maruti Vitara Brezza,2018,Diesel,Automatic,"34,311 Kms",1st Owner,Pune,"₹ 9,96,500"
1,2016 Maruti Swift Dzire,2016 Maruti Swift Dzire,2016 Maruti Swift Dzire,2015,Diesel,Manual,"95,297 Kms",1st Owner,Pune,"₹ 7,50,000"
2,2015 Maruti Swift Dzire,2015 Maruti Swift Dzire,2015 Maruti Swift Dzire,2015,Petrol,Manual,"41,993 Kms",1st Owner,Pune,"₹ 5,30,500"
3,2015 Maruti Ciaz,2015 Maruti Ciaz,2015 Maruti Ciaz,2015,Petrol,MH12,"64,343 Kms",1st Owner,Pune,"₹ 5,49,500"
4,2018 Maruti Celerio,2018 Maruti Celerio,2018 Maruti Celerio,2018,Petrol,Automatic,"26,689 Kms",1st Owner,Pune,"₹ 5,51,500"
5,2014 Maruti Celerio,2014 Maruti Celerio,2014 Maruti Celerio,2014,Petrol,Manual,"86,794 Kms",1st Owner,Pune,"₹ 3,59,431"
6,2014 Maruti Wagon R,2014 Maruti Wagon R,2014 Maruti Wagon R,2014,Petrol,Manual,"28,181 Kms",1st Owner,Pune,"₹ 3,83,500"
7,2019 Hyundai Santro,2019 Hyundai Santro,2019 Hyundai Santro,2018,Petrol,Manual,"21,817 Kms",1st Owner,Pune,"₹ 4,76,000"
8,2017 Maruti Alto K10,2017 Maruti Alto K10,2017 Maruti Alto K10,2016,Petrol,Manual,"6,707 Kms",1st Owner,Pune,"₹ 3,74,500"
9,2014 Hyundai i10,2014 Hyundai i10,2014 Hyundai i10,2014,Petrol,Manual,"96,569 Kms",1st Owner,Pune,"₹ 3,57,000"
10,2020 Maruti Alto 800,2020 Maruti Alto 800,2020 Maruti Alto 800,2019,Petrol,MH12,"19,945 Kms",1st Owner,Pune,"₹ 3,88,500"
11,2015 Maruti Wagon R,2015 Maruti Wagon R,2015 Maruti Wagon R,2015,Petrol,Manual,"58,035 Kms",1st Owner,Pune,"₹ 3,84,000"
12,2014 Fiat Grande Punto,2014 Fiat Grande Punto,2014 Fiat Grande Punto,2014,Diesel,MH14,"75,291 Kms",1st Owner,Pune,"₹ 3,56,500"
13,2017 Maruti Ignis,2017 Maruti Ignis,2017 Maruti Ignis,2017,Petrol,Manual,"83,478 Kms",1st Owner,Pune,"₹ 5,13,500"
14,-,-,-,-,-,-,-,-,Pune,-
15,-,-,-,-,-,-,-,-,Pune,-
16,-,-,-,-,-,-,-,-,Pune,-
17,-,-,-,-,-,-,-,-,Pune,-
18,-,-,-,-,-,-,-,-,Pune,-
19,-,-,-,-,-,-,-,-,Pune,-
20,2016 Maruti Wagon R,2016 Maruti Wagon R,2016 Maruti Wagon R,2016,Petrol,Automatic,"18,363 Kms",1st Owner,Pune,"₹ 4,44,500"
21,2018 Ford Figo Aspire,2018 Ford Figo Aspire,2018 Ford Figo Aspire,2018,Petrol,Manual,"17,439 Kms",1st Owner,Pune,"₹ 6,00,000"
22,2018 Maruti Celerio,2018 Maruti Celerio,2018 Maruti Celerio,2018,Petrol,Automatic,"21,855 Kms",1st Owner,Pune,"₹ 5,58,000"
23,2018 Maruti Wagon R,2018 Maruti Wagon R,2018 Maruti Wagon R,2017,Petrol,Automatic,"23,604 Kms",1st Owner,Pune,"₹ 4,75,500"
24,2017 Maruti Alto 800,2017 Maruti Alto 800,2017 Maruti Alto 800,2017,Petrol,Manual,"50,351 Kms",1st Owner,Pune,"₹ 3,17,381"
25,2014 Maruti Wagon R,2014 Maruti Wagon R,2014 Maruti Wagon R,2014,Petrol,Manual,"28,181 Kms",1st Owner,Pune,"₹ 3,83,500"
26,2019 Maruti Vitara Brezza,2019 Maruti Vitara Brezza,2019 Maruti Vitara Brezza,2018,Diesel,Automatic,"34,311 Kms",1st Owner,Pune,"₹ 9,96,500"
27,2014 Maruti Wagon R,2014 Maruti Wagon R,2014 Maruti Wagon R,2014,Petrol,Manual,"89,043 Kms",2nd Owner,Pune,"₹ 3,08,500"
28,2017 Maruti Celerio,2017 Maruti Celerio,2017 Maruti Celerio,2017,Petrol,MH12,"75,383 Kms",1st Owner,Pune,"₹ 5,14,500"
29,2016 Maruti Celerio,2016 Maruti Celerio,2016 Maruti Celerio,2016,Petrol,Automatic,"27,590 Kms",1st Owner,Pune,"₹ 5,01,500"
30,2016 Maruti Wagon R,2016 Maruti Wagon R,2016 Maruti Wagon R,2016,Petrol,Manual,"23,918 Kms",1st Owner,Pune,"₹ 3,81,500"
31,2016 Maruti Wagon R,2016 Maruti Wagon R,2016 Maruti Wagon R,2016,Petrol,Manual,"30,571 Kms",1st Owner,Pune,"₹ 4,21,000"
32,2016 Maruti Ritz,2016 Maruti Ritz,2016 Maruti Ritz,2015,Petrol,Manual,"32,398 Kms",1st Owner,Pune,"₹ 4,22,500"
33,2017 Maruti Vitara Brezza,2017 Maruti Vitara Brezza,2017 Maruti Vitara Brezza,2017,Diesel,Manual,"78,514 Kms",1st Owner,Pune,"₹ 8,77,000"
34,2016 Mahindra XUV500,2016 Mahindra XUV500,2016 Mahindra XUV500,2016,Diesel,Manual,"71,288 Kms",1st Owner,Pune,"₹ 8,67,000"
35,2018 Maruti Wagon R,2018 Maruti Wagon R,2018 Maruti Wagon R,2017,CNG,Manual,"42,619 Kms",1st Owner,Pune,"₹ 4,93,500"
36,2015 Maruti Wagon R,2015 Maruti Wagon R,2015 Maruti Wagon R,2015,Petrol,MH12,"40,647 Kms",1st Owner,Pune,"₹ 3,96,500"
37,2014 Hyundai Grand i10,2014 Hyundai Grand i10,2014 Hyundai Grand i10,2014,Petrol,Automatic,"54,936 Kms",2nd Owner,Pune,"₹ 4,56,570"
38,2016 Maruti Celerio,2016 Maruti Celerio,2016 Maruti Celerio,2016,Petrol,Manual,"55,669 Kms",1st Owner,Pune,"₹ 4,23,500"
39,2015 Hyundai i20,2015 Hyundai i20,2015 Hyundai i20,2015,Petrol,MH12,"42,578 Kms",2nd Owner,Pune,"₹ 5,58,500"
40,2015 Maruti Wagon R,2015 Maruti Wagon R,2015 Maruti Wagon R,2015,Petrol,MH12,"24,122 Kms",1st Owner,Pune,"₹ 4,68,500"
41,2015 Maruti Swift Dzire,2015 Maruti Swift Dzire,2015 Maruti Swift Dzire,2015,Petrol,MH12,"73,134 Kms",1st Owner,Pune,"₹ 5,30,000"
42,2012 Hyundai i20,2012 Hyundai i20,2012 Hyundai i20,2011,Petrol,Manual,"50,796 Kms",1st Owner,Pune,"₹ 2,94,500"
43,2019 Maruti Alto 800,2019 Maruti Alto 800,2019 Maruti Alto 800,2017,Petrol,Manual,"90,516 Kms",1st Owner,Pune,"₹ 3,26,500"
44,2017 Maruti Ciaz,2017 Maruti Ciaz,2017 Maruti Ciaz,2017,Petrol,Automatic,"25,877 Kms",1st Owner,Pune,"₹ 8,43,500"
45,2018 Hyundai i20,2018 Hyundai i20,2018 Hyundai i20,2018,Petrol,Automatic,"17,908 Kms",1st Owner,Pune,"₹ 7,65,500"
46,2017 Maruti Vitara Brezza,2017 Maruti Vitara Brezza,2017 Maruti Vitara Brezza,2017,Diesel,Manual,"60,710 Kms",1st Owner,Pune,"₹ 8,37,500"
47,2019 Honda Amaze,2019 Honda Amaze,2019 Honda Amaze,2018,Petrol,Manual,"9,618 Kms",1st Owner,Pune,"₹ 6,06,500"
48,2018 Maruti Alto K10,2018 Maruti Alto K10,2018 Maruti Alto K10,2018,Petrol,Manual,"13,625 Kms",1st Owner,Pune,"₹ 3,59,500"
49,2016 Hyundai Grand i10,2016 Hyundai Grand i10,2016 Hyundai Grand i10,2015,Petrol,Manual,"61,631 Kms",1st Owner,Pune,"₹ 4,71,000"
50,2017 Maruti Wagon R,2017 Maruti Wagon R,2017 Maruti Wagon R,2017,Petrol,Manual,"50,296 Kms",1st Owner,Pune,"₹ 4,52,500"
51,2016 Maruti Wagon R,2016 Maruti Wagon R,2016 Maruti Wagon R,2016,Petrol,Manual,"62,550 Kms",1st Owner,Pune,"₹ 3,89,000"
52,2014 Maruti Wagon R,2014 Maruti Wagon R,2014 Maruti Wagon R,2013,Petrol,Manual,"55,059 Kms",1st Owner,Pune,"₹ 3,46,000"
53,2017 Maruti Wagon R,2017 Maruti Wagon R,2017 Maruti Wagon R,2017,Petrol,Manual,"24,273 Kms",1st Owner,Pune,"₹ 4,65,000"
54,2017 Maruti Wagon R,2017 Maruti Wagon R,2017 Maruti Wagon R,2017,Petrol,Manual,"52,758 Kms",1st Owner,Pune,"₹ 4,55,500"
55,2018 Maruti Ciaz,2018 Maruti Ciaz,2018 Maruti Ciaz,2018,Petrol,Manual,"10,265 Kms",1st Owner,Pune,"₹ 8,40,000"
56,2020 Hyundai Santro,2020 Hyundai Santro,2020 Hyundai Santro,2019,Petrol,Automatic,"4,521 Kms",1st Owner,Pune,"₹ 5,91,500"
57,2017 Maruti Celerio,2017 Maruti Celerio,2017 Maruti Celerio,2017,Petrol,Automatic,"14,896 Kms",2nd Owner,Pune,"₹ 5,85,000"
58,2016 Hyundai Grand i10,2016 Hyundai Grand i10,2016 Hyundai Grand i10,2015,Petrol,Automatic,"62,193 Kms",2nd Owner,Pune,"₹ 4,72,500"
59,2016 Maruti Wagon R,2016 Maruti Wagon R,2016 Maruti Wagon R,2016,Petrol,Manual,"33,021 Kms",1st Owner,Pune,"₹ 4,27,000"

In [31]:
df.to_csv("pune.csv")

In [2]:
driver = webdriver.Chrome('chromedriver.exe')
driver.get("https://www.cardekho.com/")

In [17]:
# car search for hyderabad
driver.get(driver.find_element_by_xpath("//nav[@class='gsc_col-sm-12 gsc_col-md-12']/ul/li[2]/ul/li/ul/li[5]/a").get_attribute("href"))

In [18]:
for i in range(1000):
    driver.execute_script("window.scrollBy(0,100)")
    time.sleep(2)

In [19]:
urls=[]
for i in driver.find_elements_by_xpath("//div[@class='gsc_col-xs-7 carsName']/a"):
    urls.append(i.get_attribute("href"))

In [21]:
len(urls)

139

In [22]:
brand=[]
model=[]
variant=[]
year=[]
fuel=[]
transmission=[]
km=[]
owners=[]
location=[]
price=[]


for i in urls:
    driver.get(i)
    time.sleep(3)
    try:
        brand.append(driver.find_element_by_xpath("/html/body/div[2]/div/div[1]/div/div/main/div/div/div[2]/div[1]/div/div/div/div[1]/div[1]/h1").text)
    except NoSuchElementException:
        brand.append('-')
    try:
        model.append(driver.find_element_by_xpath("/html/body/div[2]/div/div[1]/div/div/main/div/div/div[2]/div[1]/div/div/div/div[1]/div[1]/h1").text)
    except NoSuchElementException:
        model.append('-')
    try:
        variant.append(driver.find_element_by_xpath("/html/body/div[2]/div/div[1]/div/div/main/div/div/div[2]/div[1]/div/div/div/div[1]/div[1]/h1").text)
    except NoSuchElementException:
        variant.append('-')
    try:
        year.append(driver.find_element_by_xpath("/html/body/div[2]/div/div[1]/div/div/main/div/div/div[1]/div[3]/div/div/div/ul/li[1]/div/div[2]").text)
    except NoSuchElementException:
        year.append('-')
    try:
        fuel.append(driver.find_element_by_xpath("/html/body/div[2]/div/div[1]/div/div/main/div/div/div[1]/div[3]/div/div/div/ul/li[3]/div/div[2]").text)
    except NoSuchElementException:
        fuel.append('-')
    try:
        transmission.append(driver.find_element_by_xpath("/html/body/div[2]/div/div[1]/div/div/main/div/div/div[1]/div[3]/div/div/div/ul/li[8]/div/div[2]").text)
    except NoSuchElementException:
        transmission.append('-')
    try:
        km.append(driver.find_element_by_xpath("/html/body/div[2]/div/div[1]/div/div/main/div/div/div[1]/div[3]/div/div/div/ul/li[4]/div/div[2]").text)
    except NoSuchElementException:
        km.append('-')
    try:
        owners.append(driver.find_element_by_xpath("/html/body/div[2]/div/div[1]/div/div/main/div/div/div[1]/div[3]/div/div/div/ul/li[6]/div/div[2]").text)
    except NoSuchElementException:
        owners.append('-')
        
    location.append("hyderabad")
    try:
        price.append(driver.find_element_by_xpath("//div[@class='priceSection']").text)
    except NoSuchElementException:
        price.append('-')

In [23]:
df=pd.DataFrame({})
df['Brand']=brand
df['model']=model
df['variant']=variant
df['year']=year
df['fuel']=fuel
df['transmission']=transmission
df['km driven']=km
df['No of owners']=owners
df['location']=location
df['price']=price
df

,Brand,model,variant,year,fuel,transmission,km driven,No of owners,location,price
0,2018 Maruti Swift Dzire,2018 Maruti Swift Dzire,2018 Maruti Swift Dzire,2017,Petrol,Manual,"38,463 Kms",1st Owner,hyderabad,"₹ 6,33,500"
1,2017 Maruti Ignis,2017 Maruti Ignis,2017 Maruti Ignis,2017,Petrol,Manual,"19,957 Kms",1st Owner,hyderabad,"₹ 5,73,500"
2,2019 Maruti Vitara Brezza,2019 Maruti Vitara Brezza,2019 Maruti Vitara Brezza,2018,Diesel,Automatic,"21,109 Kms",1st Owner,hyderabad,"₹ 8,63,500"
3,2015 Maruti Swift,2015 Maruti Swift,2015 Maruti Swift,2015,Petrol,Manual,"66,487 Kms",1st Owner,hyderabad,"₹ 4,45,500"
4,2017 Honda Jazz,2017 Honda Jazz,2017 Honda Jazz,2015,Petrol,Manual,"38,339 Kms",2nd Owner,hyderabad,"₹ 5,65,500"
...,...,...,...,...,...,...,...,...,...,...
134,2015 Maruti Alto K10,2015 Maruti Alto K10,2015 Maruti Alto K10,2014,Petrol,Manual,"34,842 Kms",1st Owner,hyderabad,"₹ 3,46,000"
135,2016 Hyundai i10,2016 Hyundai i10,2016 Hyundai i10,2015,Petrol,Manual,"35,758 Kms",1st Owner,hyderabad,"₹ 4,28,500"
136,-,-,-,-,-,-,-,-,hyderabad,-
137,-,-,-,-,-,-,-,-,hyderabad,-
138,-,-,-,-,-,-,-,-,hyderabad,-

In [24]:
df.to_csv("hyderabad.csv")

In [8]:
driver = webdriver.Chrome('chromedriver.exe')
driver.get("https://www.cardekho.com/")

In [10]:
# car search for delhi
driver.get(driver.find_element_by_xpath("//nav[@class='gsc_col-sm-12 gsc_col-md-12']/ul/li[2]/ul/li/ul/li[4]/a").get_attribute("href"))

In [11]:
for i in range(1000):
    driver.execute_script("window.scrollBy(0,100)")
    time.sleep(2)

In [12]:
urls=[]
for i in driver.find_elements_by_xpath("//div[@class='gsc_col-xs-7 carsName']/a"):
    urls.append(i.get_attribute("href"))
len(urls)

458

In [14]:
brand=[]
model=[]
variant=[]
year=[]
fuel=[]
transmission=[]
km=[]
owners=[]
location=[]
price=[]


for i in urls:
    driver.get(i)
    time.sleep(3)
    try:
        brand.append(driver.find_element_by_xpath("/html/body/div[2]/div/div[1]/div/div/main/div/div/div[2]/div[1]/div/div/div/div[1]/div[1]/h1").text)
    except NoSuchElementException:
        brand.append('-')
    try:
        model.append(driver.find_element_by_xpath("/html/body/div[2]/div/div[1]/div/div/main/div/div/div[2]/div[1]/div/div/div/div[1]/div[1]/h1").text)
    except NoSuchElementException:
        model.append('-')
    try:
        variant.append(driver.find_element_by_xpath("/html/body/div[2]/div/div[1]/div/div/main/div/div/div[2]/div[1]/div/div/div/div[1]/div[1]/h1").text)
    except NoSuchElementException:
        variant.append('-')
    try:
        year.append(driver.find_element_by_xpath("/html/body/div[2]/div/div[1]/div/div/main/div/div/div[1]/div[3]/div/div/div/ul/li[1]/div/div[2]").text)
    except NoSuchElementException:
        year.append('-')
    try:
        fuel.append(driver.find_element_by_xpath("/html/body/div[2]/div/div[1]/div/div/main/div/div/div[1]/div[3]/div/div/div/ul/li[3]/div/div[2]").text)
    except NoSuchElementException:
        fuel.append('-')
    try:
        transmission.append(driver.find_element_by_xpath("/html/body/div[2]/div/div[1]/div/div/main/div/div/div[1]/div[3]/div/div/div/ul/li[8]/div/div[2]").text)
    except NoSuchElementException:
        transmission.append('-')
    try:
        km.append(driver.find_element_by_xpath("/html/body/div[2]/div/div[1]/div/div/main/div/div/div[1]/div[3]/div/div/div/ul/li[4]/div/div[2]").text)
    except NoSuchElementException:
        km.append('-')
    try:
        owners.append(driver.find_element_by_xpath("/html/body/div[2]/div/div[1]/div/div/main/div/div/div[1]/div[3]/div/div/div/ul/li[6]/div/div[2]").text)
    except NoSuchElementException:
        owners.append('-')
        
    location.append("delhi")
    try:
        price.append(driver.find_element_by_xpath("//div[@class='priceSection']").text)
    except NoSuchElementException:
        price.append('-')

In [15]:
df=pd.DataFrame({})
df['Brand']=brand
df['model']=model
df['variant']=variant
df['year']=year
df['fuel']=fuel
df['transmission']=transmission
df['km driven']=km
df['No of owners']=owners
df['location']=location
df['price']=price
df

,Brand,model,variant,year,fuel,transmission,km driven,No of owners,location,price
0,2014 Maruti Swift,2014 Maruti Swift,2014 Maruti Swift,2014,Diesel,Manual,"66,737 Kms",1st Owner,delhi,"₹ 4,02,500"
1,2018 Maruti Ignis,2018 Maruti Ignis,2018 Maruti Ignis,2018,Petrol,Automatic,"17,011 Kms",1st Owner,delhi,"₹ 5,64,212"
2,2017 Tata Tiago,2017 Tata Tiago,2017 Tata Tiago,2017,Petrol,Automatic,"19,544 Kms",1st Owner,delhi,"₹ 4,50,000"
3,2015 Maruti Swift,2015 Maruti Swift,2015 Maruti Swift,2015,Petrol,Manual,"79,620 Kms",1st Owner,delhi,"₹ 3,68,500"
4,2016 Tata Bolt,2016 Tata Bolt,2016 Tata Bolt,2015,Petrol,Manual,"30,791 Kms",1st Owner,delhi,"₹ 2,94,500"
...,...,...,...,...,...,...,...,...,...,...
453,2017 Renault KWID,2017 Renault KWID,2017 Renault KWID,2016,Petrol,Manual,"32,933 Kms",1st Owner,delhi,"₹ 2,77,746"
454,2018 Maruti Alto 800,2018 Maruti Alto 800,2018 Maruti Alto 800,2018,Petrol,Manual,"49,645 Kms",1st Owner,delhi,"₹ 2,97,523"
455,2016 Maruti Swift Dzire,2016 Maruti Swift Dzire,2016 Maruti Swift Dzire,2016,Petrol,Manual,"35,687 Kms",1st Owner,delhi,"₹ 4,12,500"
456,2016 Honda City,2016 Honda City,2016 Honda City,2016,Petrol,Manual,"55,061 Kms",1st Owner,delhi,"₹ 7,25,600"
457,-,-,-,-,-,-,-,-,delhi,-

In [16]:
df.to_csv("delhi.csv")

In [2]:
import pandas as pd
df1=pd.read_csv("olx.csv")
df2=pd.read_csv("ahmed.csv")
df3=pd.read_csv("chennai.csv")
df4=pd.read_csv("hyderabad.csv")
df5=pd.read_csv("pune.csv")
df6=pd.read_csv("bangalore.csv")
df7=pd.read_csv("delhi.csv")
df8=pd.read_csv("kolkata.csv")

In [3]:
df=pd.concat([df1,df2,df3,df4,df5,df6,df7,df8],axis=0)
df

,Unnamed: 0,Brand,model,variant,year,fuel,transmission,km driven,No of owners,location,price
0,0,-,-,-,-,-,-,-,-,pune,-
1,1,-,-,-,-,-,-,-,-,pune,-
2,2,-,-,-,-,-,-,-,-,pune,-
3,3,-,-,-,-,-,-,-,-,pune,-
4,4,-,-,-,-,-,-,-,-,pune,-
...,...,...,...,...,...,...,...,...,...,...,...
95,95,2015Mahindra Bolero 2011-2019 SLX,2015Mahindra Bolero 2011-2019 SLX,2015Mahindra Bolero 2011-2019 SLX,2015,Diesel,Manual,"1,39,139 kms",First Owner,kolkata,4.75 Lakh*
96,96,2016Maruti Swift LDI BSIV,2016Maruti Swift LDI BSIV,2016Maruti Swift LDI BSIV,2016,Diesel,Manual,"1,30,130 kms",First Owner,kolkata,3.95 Lakh*
97,97,2016Toyota Innova Crysta 2016-2020 2.4 ZX MT BSIV,2016Toyota Innova Crysta 2016-2020 2.4 ZX MT BSIV,2016Toyota Innova Crysta 2016-2020 2.4 ZX MT BSIV,2016,Diesel,Manual,"35,000 kms",First Owner,kolkata,16.75 Lakh*
98,98,2015Honda City i VTEC SV,2015Honda City i VTEC SV,2015Honda City i VTEC SV,2015,Petrol,Manual,"34,295 kms",First Owner,kolkata,5.65 Lakh*
99,99,2016Volkswagen Ameo 1.2 MPI Highline,2016Volkswagen Ameo 1.2 MPI Highline,2016Volkswagen Ameo 1.2 MPI Highline,2016,Petrol,Manual,"32,000 kms",First Owner,kolkata,4.75 Lakh*

In [4]:
df.to_csv("car.csv")